# This workflow will upload a Maven package when a release is created

name: Upload Maven Package

on:
  release:
    types: [published]
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v5
    - name: Set up Java and Maven Central Repository
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: central-portal
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        cache: maven
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG
    - name: Build and deploy with Maven
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: |
        mvn --batch-mode -Dgpg.passphrase="" clean compile verify package javadoc:aggregate-jar deploy
